
networks:
  ordini_network:
    driver: bridge

volumes:
  ordini_order_db_data:

services:

  postgresdb:
    image: postgres:latest
    container_name: ordini_order_postgres
    restart: on-failure
    environment:
      POSTGRES_USER: ${DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${DATASOURCE_PASSWORD}
      POSTGRES_DB: ${DATASOURCE_DATABASE}
    command: -p 5434
    expose:
      - "5434"
    ports:
      - "5434:5434"
    healthcheck:
      test: [
        "CMD-SHELL",
        "pg_isready -h localhost -p 5434 -U ${DATASOURCE_USERNAME} -d ${DATASOURCE_DATABASE}",
      ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      - ordini_network
    volumes:
      - ordini_order_db_data:/var/lib/postgresql/data

  app:
    container_name: ordini_order
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8082:8082"
    environment:
      DATASOURCE_URL: ${DATASOURCE_DATABASE}
      DATASOURCE_USERNAME: ${DATASOURCE_USERNAME}
      DATASOURCE_PASSWORD: ${DATASOURCE_PASSWORD}
      SERVER_PORT: 8082
    depends_on:
      postgresdb:
        condition: service_healthy
    networks:
      - ordini_network